#!/bin/sh

prefix=`date '+%Y%m%d_%H%M'`

send_id="$(ps -ef | grep 'ReceiveDaemon 9300' | grep -v grep | grep -v tail)"

if [ ! "${send_id}" = "" ]; then
    echo "Kibrsvr9300 Daemon Already Start!!!!!";
    exit;
fi;

mv /HIC_APP/daemon/log_dev/kibrsvr_9300.log /HIC_APP/daemon/log_dev/kibrsvr_9300_${prefix}.log
nohup java -classpath /HIC_APP/daemon/lib/xutil.jar:/HIC_APP/daemon/class rsvr.ReceiveDaemon 9300 172.20.102.41 9300 >> /HIC_APP/daemon/log_dev/kibrsvr_9300.log &
