#!/bin/sh

prefix=`date '+%Y%m%d_%H%M'`

send_id="$(ps -ef | grep 9130)"

if [ ! "${send_id}" = "" ]; then
    echo "Kib Daemon Already Start!!!!!";
    exit;
fi;

mv /HIC_APP/daemon/log_dev/kib.log /HIC_APP/daemon/log_dev/kib${prefix}.log
nohup java -classpath /HIC_APP/daemon/lib/xutil.jar:/HIC_APP/daemon/class ssvr.SendDaemon 9130 192.168.4.200 50811 >> /HIC_APP/daemon/log_dev/kib.log &
