#!/bin/sh

prefix=`date '+%Y%m%d_%H%M'`

#send_id="$(ps -ef | grep 9120)"

#if [ ! "${send_id}" = "" ]; then
#    echo "Nice 1F00 Daemon Already Start!!!!!";
#    exit;
#fi;

mv /HIC_APP/daemon/log_dev/nice1f.log /HIC_APP/daemon/log_dev/nice1f${prefix}.log
nohup java -classpath /HIC_APP/daemon/lib/xutil.jar:/HIC_APP/daemon/class ssvr.SendDaemon 9120 203.234.213.51 28099 >> /HIC_APP/daemon/log_dev/nice1f.log &
