#!/bin/sh

prefix=`date '+%Y%m%d_%H%M'`

send_id="$(ps -ef | grep 9300)"

if [ ! "${send_id}" = "" ]; then
    echo "Kibrsvr9300 Daemon Already Start!!!!!";
#    exit;
fi;

mv /HIC_APP/daemon/log_dev/kibrsvr.log /HIC_APP/daemon/lo_devg/kibrsvr${prefix}.log
nohup java -classpath /HIC_APP/daemon/lib/xutil.jar:/HIC_APP/daemon/class rsvr.ReceiveDaemon 9300 172.20.102.11 9300 >> /HIC_APP/daemon/log_dev/kibrsvr.log &
