#!/bin/sh

send_id="$(ps -ef | grep 'SendDaemonLocalReturn 9230' |grep -v grep | grep -v tail | cut -c10-16)";

if [ ! "${send_id}" = "" ]; then
	kill -9 ${send_id};
	echo "Kib Daemon Down !!";
else 
	echo "Already Kib Daemon Down!!"
fi;
