#!/bin/sh

send_id="$(ps -ef | grep 9310 |grep -v grep|grep -v db2agent|cut -c10-16)";

if [ ! "${send_id}" = "" ]; then
	kill -9 ${send_id};
	echo "Kibrsvr9310 Daemon Down !!";
else 
	echo "Already Kibrsvr9310 Daemon Down!!"
fi;
