#!/bin/sh

kib_id="$(ps -ef | grep 9300 | grep KibReceiver | grep -v grep | grep -v tail |cut -c10-16)"

if [ ! "${kib_id}" = "" ]; then
	kill -9  ${kib_id};
	echo "KibReceiver Server Down !!!"
else
	echo "Already KibReceiver Server Down !!!"
fi

