
SELECT * FROM NUSER.HPG_ONLN_AUTO_LOAN_APPL@HOMEDB1 A
;

SELECT * FROM AUSER.APDT_PRDT_BASE B
;

SELECT * 
FROM   NUSER.HPG_ONLN_AUTO_LOAN_APPL@HOMEDB1 A
       LEFT OUTER JOIN AUSER.APDT_PRDT_BASE B
       ON A.PRDT_CD = B.PRDT_CD
;

