
--create table alot_mo_acnt_base_real_111221 as
--select * from auser.alot_mo_acnt_base@hiplus_link
;


--create table AUSER.ALOT_MO_ACNT_BASE_20111221 as
--select * from AUSER.ALOT_MO_ACNT_BASE
--;

--select * from alot_mo_acnt_base_real_111221;

--ALTER TABLE ALOT_MO_ACNT_BASE_real_111221 ADD(
--	CONSTRAINT ACNTT_BASE_PK PRIMARY KEY (BSN_DIV_CD, BANK_CD, MO_ACNT_NO));

--alter table alot_mo_acnt_base_REAL_111221 drop CONSTRAINT SYS_C0021617;

--select constraint_name
--from user_constraints
--where table_name = 'auser.alot_mo_acnt_base'
--;


-- 모계좌테이블 프라이머리키 수정 쿼리
--alter table auser.alot_mo_acnt_base drop CONSTRAINT ALOT_MO_ACNT_BASE_PK;
--ALTER TABLE auser.ALOT_MO_ACNT_BASE ADD(CONSTRAINT ALOT_MO_ACNT_BASE_PK PRIMARY KEY (BSN_DIV_CD, BANK_CD));

-- 추후 우리은행 계좌 추가 후, 수정 할 것.
--alter table auser.alot_mo_acnt_base drop CONSTRAINT ALOT_MO_ACNT_BASE_PK;
--ALTER TABLE auser.ALOT_MO_ACNT_BASE ADD(CONSTRAINT ALOT_MO_ACNT_BASE_PK PRIMARY KEY (BSN_DIV_CD, BANK_CD, MO_ACNT_NO));

--ALTER TABLE TABLE명 DROP CONSTRAINT PK명;

-- PK 제거하기
--Alter TABLE 테이블이름 drop primary key cascade
 
--PK추가 하기
--ALTER TABLE 테이블이름 ADD CONSTRAINT 인덱스 이름 PRIMARY KEY(field1, field2)

-------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------

--CREATE TABLE alot_mo_acnt_base_20111205 AS (select * from AUSER.ALOT_MO_ACNT_BASE);
--select * from alot_mo_acnt_base_20111205;

--drop table auser.ALOT_MO_ACNT_BASE;

--insert into AUSER.ALOT_MO_ACNT_BASE
--select * from alot_mo_acnt_base_20111205 order by BSN_DIV_CD, BANK_CD, MO_ACNT_NO;
--
--commit;



-- DDL Script for TABLE AUSER.ALOT_MO_ACNT_BASE. Orange for ORACLE.
-- Generated on 2011/12/05 14:32:47 by ZUSER@CABISDEV

CREATE TABLE AUSER.ALOT_MO_ACNT_BASE 
(
	BSN_DIV_CD         CHAR (2) DEFAULT '' NOT NULL,
	BANK_CD            CHAR (3) DEFAULT '' NOT NULL,
	MO_ACNT_NO         VARCHAR2 (20) DEFAULT '' NOT NULL,
	RMRK               VARCHAR2 (100) DEFAULT '',
	FRST_REG_DT        CHAR (10) DEFAULT '',
	FRST_REG_TM        CHAR (6) DEFAULT '',
	FRST_REG_EMP_NO    VARCHAR2 (8) DEFAULT '',
	LAST_PROC_DT       CHAR (10) DEFAULT '',
	LAST_PROC_TM       CHAR (6) DEFAULT '',
	LAST_PROC_EMP_NO   VARCHAR2 (8) DEFAULT ''
)
TABLESPACE AUSER
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE
(
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	MAXEXTENTS UNLIMITED
	BUFFER_POOL DEFAULT
)
LOGGING
DISABLE ROW MOVEMENT ;

GRANT DELETE ON AUSER.ALOT_MO_ACNT_BASE TO ZUSER;
GRANT INSERT ON AUSER.ALOT_MO_ACNT_BASE TO ZUSER;
GRANT SELECT ON AUSER.ALOT_MO_ACNT_BASE TO ZUSER;
GRANT UPDATE ON AUSER.ALOT_MO_ACNT_BASE TO ZUSER;

COMMENT ON TABLE AUSER.ALOT_MO_ACNT_BASE IS 'ALOT_모계좌_기본' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.BANK_CD IS '은행_코드' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.BSN_DIV_CD IS '업무_구분코드' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.FRST_REG_DT IS '최초_등록_일자' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.FRST_REG_EMP_NO IS '최초_등록_사원번호' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.FRST_REG_TM IS '최초_등록_시각' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.LAST_PROC_DT IS '최종_처리_일자' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.LAST_PROC_EMP_NO IS '최종_처리_사원번호' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.LAST_PROC_TM IS '최종_처리_시각' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.MO_ACNT_NO IS '모_계좌번호' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.RMRK IS '비고' ;

CREATE UNIQUE INDEX AUSER.ACNTT_BASE_PK 
ON AUSER.ALOT_MO_ACNT_BASE
(
	BSN_DIV_CD ASC
	, BANK_CD ASC
	, MO_ACNT_NO ASC
)
TABLESPACE AUSER
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE
(
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	MAXEXTENTS UNLIMITED
	BUFFER_POOL DEFAULT
)
LOGGING
NOCOMPRESS
NOPARALLEL ;

--ALTER TABLE AUSER.ALOT_MO_ACNT_BASE ADD(PRIMARY KEY (BSN_DIV_CD, BANK_CD, MO_ACNT_NO));
ALTER TABLE AUSER.ALOT_MO_ACNT_BASE ADD(CONSTRAINT ALOT_MO_ACNT_BASE_PK PRIMARY KEY (BSN_DIV_CD, BANK_CD));

