
--CREATE TABLE alot_mo_acnt_base_20111205 AS (select * from AUSER.ALOT_MO_ACNT_BASE);
--select * from alot_mo_acnt_base_20111205;

--drop table auser.ALOT_MO_ACNT_BASE;

--insert into AUSER.ALOT_MO_ACNT_BASE
--select * from alot_mo_acnt_base_20111205 order by BSN_DIV_CD, BANK_CD, MO_ACNT_NO;
--
--commit;



-- DDL Script for TABLE AUSER.ALOT_MO_ACNT_BASE. Orange for ORACLE.
-- Generated on 2011/12/05 14:32:47 by ZUSER@CABISDEV

CREATE TABLE AUSER.ALOT_MO_ACNT_BASE 
(
	BSN_DIV_CD         CHAR (2) DEFAULT '' NOT NULL,
	BANK_CD            CHAR (3) DEFAULT '' NOT NULL,
	MO_ACNT_NO         VARCHAR2 (20) DEFAULT '' NOT NULL,
	RMRK               VARCHAR2 (100) DEFAULT '',
	FRST_REG_DT        CHAR (10) DEFAULT '',
	FRST_REG_TM        CHAR (6) DEFAULT '',
	FRST_REG_EMP_NO    VARCHAR2 (8) DEFAULT '',
	LAST_PROC_DT       CHAR (10) DEFAULT '',
	LAST_PROC_TM       CHAR (6) DEFAULT '',
	LAST_PROC_EMP_NO   VARCHAR2 (8) DEFAULT ''
)
TABLESPACE AUSER
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE
(
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	MAXEXTENTS UNLIMITED
	BUFFER_POOL DEFAULT
)
LOGGING
DISABLE ROW MOVEMENT ;

GRANT DELETE ON AUSER.ALOT_MO_ACNT_BASE TO ZUSER;
GRANT INSERT ON AUSER.ALOT_MO_ACNT_BASE TO ZUSER;
GRANT SELECT ON AUSER.ALOT_MO_ACNT_BASE TO ZUSER;
GRANT UPDATE ON AUSER.ALOT_MO_ACNT_BASE TO ZUSER;

COMMENT ON TABLE AUSER.ALOT_MO_ACNT_BASE IS 'ALOT_모계좌_기본' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.BANK_CD IS '은행_코드' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.BSN_DIV_CD IS '업무_구분코드' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.FRST_REG_DT IS '최초_등록_일자' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.FRST_REG_EMP_NO IS '최초_등록_사원번호' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.FRST_REG_TM IS '최초_등록_시각' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.LAST_PROC_DT IS '최종_처리_일자' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.LAST_PROC_EMP_NO IS '최종_처리_사원번호' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.LAST_PROC_TM IS '최종_처리_시각' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.MO_ACNT_NO IS '모_계좌번호' ;

COMMENT ON COLUMN AUSER.ALOT_MO_ACNT_BASE.RMRK IS '비고' ;

CREATE UNIQUE INDEX AUSER.ACNTT_BASE_PK 
ON AUSER.ALOT_MO_ACNT_BASE
(
	BSN_DIV_CD ASC
	, BANK_CD ASC
	, MO_ACNT_NO ASC
)
TABLESPACE AUSER
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE
(
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	MAXEXTENTS UNLIMITED
	BUFFER_POOL DEFAULT
)
LOGGING
NOCOMPRESS
NOPARALLEL ;

ALTER TABLE AUSER.ALOT_MO_ACNT_BASE ADD(
	PRIMARY KEY (BSN_DIV_CD, BANK_CD, MO_ACNT_NO));

