-- 자동전표거래내역조회
SELECT A.ACCT_DT AS ACCT_DT
      ,DENSE_RANK() 
          OVER(ORDER BY A.ACCT_DT,A.TR_DESC_NO,A.TR_SNUM)      AS TR_DESC_NO
       ,A.ACCT_UNIT_CD                                         AS ACCT_UNIT_CD
       ,A.ACCT_DEPT_CD                                         AS ACCT_DEPT_CD
       ,A.ACCT_CD                                              AS ACCT_CD
       ,ISRT_DT                                                AS ISRT_DT
       ,(SELECT Z.CD_DESC_KOR_NM
           FROM GUSER.GBCT_COMM_CD_DESC Z
          WHERE Z.CD_KIND_NO = 'R00043'
            AND Z.CD_DESC_NO = A.ACCT_UNIT_CD)                 AS ACCT_UNIT_NM
       ,(SELECT Z.DEPT_NM
           FROM DUSER.DHRT_ORG Z
          WHERE Z.DEPT_CD = A.ACCT_DEPT_CD)                    AS ACCT_DEPT_NM
       ,A.TR_TP_CD                                             AS TR_TP_CD
       ,(SELECT Z.CD_DESC_KOR_NM
           FROM GUSER.GBCT_COMM_CD_DESC Z
          WHERE Z.CD_KIND_NO = 'A00068'
            AND Z.CD_DESC_NO = A.TR_TP_CD)                     AS TR_TP_NM
       ,B.VOCH_NO                                              AS VOCH_NO
       ,A.PRDT_LRGE_CLAS_CD                                    AS PRDT_LRGE_CLAS_CD
       ,A.PRDT_MID_CLAS_CD                                     AS PRDT_MID_CLAS_CD
       ,(SELECT Z.CLAS_NM
           FROM AUSER.APDT_PRDT_CLAS Z
          WHERE Z.LRGE_CLAS_CD = A.PRDT_LRGE_CLAS_CD
            AND Z.MID_CLAS_CD = A.PRDT_MID_CLAS_CD
            AND Z.CLAS_DIV_CD = '2')                           AS PRDT_NM
       ,(SELECT ACCT_NM
           FROM EUSER.EACT_ACCT Z
          WHERE Z.ACCT_CD = A.ACCT_CD
            AND Z.ACCT_YY = SUBSTR(A.ACCT_DT,1,4))             AS ACCT_NM
       ,CASE
          WHEN A.DC_DIV_CD = 'D'   THEN A.VOCH_AMT
          ELSE 0
        END                                                    AS D_VOCH_AMT
       ,CASE
          WHEN A.DC_DIV_CD = 'C'   THEN A.VOCH_AMT
          ELSE 0
        END                                                    AS C_VOCH_AMT
       ,A.LOAN_NO                                              AS LOAN_NO
       ,A.LOAN_SEQ                                             AS LOAN_SEQ
       ,(SELECT CUST_NM
            FROM AUSER.ACTT_CUST_BASE
           WHERE CUST_NO = (SELECT Z.CONT_MAN_NO
                                                   FROM AUSER.ALOT_LOAN_BASE Z
                                                  WHERE Z.LOAN_NO = A.LOAN_NO
                                                      AND Z.LOAN_SEQ = A.LOAN_SEQ)) AS CUST_NM
       ,(SELECT Z.DEPT_NM
           FROM DUSER.DHRT_ORG Z
          WHERE Z.DEPT_CD = A.OCCR_DEPT_CD)                    AS OCCR_DEPT_NM
       ,(SELECT Z.DEPT_NM
           FROM DUSER.DHRT_ORG Z
          WHERE Z.DEPT_CD = A.MNG_DEPT_CD)                     AS MNG_DEPT_NM
       ,A.ACNT_NO                                              AS ACNT_NO
       ,A.CPRT_COM_NO                                          AS CPRT_COM_NO
       ,(SELECT Z.KOR_NAME
           FROM DUSER.DHRT_EMP_BASE Z
          WHERE Z.EMP_NO = A.FRST_REG_EMP_NO)                  AS FRST_REG_EMP_NM
       ,A.FRST_REG_EMP_NO                                      AS FRST_REG_EMP_NO
       ,(SELECT Z.CD_DESC_KOR_NM
           FROM GUSER.GBCT_COMM_CD_DESC Z
          WHERE Z.CD_KIND_NO = 'R00043'
            AND Z.CD_DESC_NO = A.OCCR_ACCT_UNIT_CD)            AS OCCR_ACCT_UNIT_NM
       ,(SELECT Z.CD_DESC_KOR_NM
           FROM GUSER.GBCT_COMM_CD_DESC Z
          WHERE Z.CD_KIND_NO = 'R00043'
            AND Z.CD_DESC_NO = A.MNG_ACCT_UNIT_CD)             AS MNG_ACCT_UNIT_NM
  FROM BUSER.BCLT_CLS_SUB_DESC A
              LEFT OUTER JOIN BUSER.BCLT_CLS_BASE B
              ON B.ACCT_DT = A.ACCT_DT
              AND B.ACCT_UNIT_CD = A.ACCT_UNIT_CD
              AND B.ACCT_DEPT_CD = A.ACCT_DEPT_CD
              AND B.TRAN_TP_CD = A.TRAN_TP_CD
              AND B.TRAN_NO = A.TRAN_NO
--WHERE  ?condition
where a.acct_dt = '2011-12-20'
;

select * from BUSER.BCLT_CLS_SUB_DESC A
where a.acct_dt = '2011-12-20'
and tr_tp_cd = 'R0030'
;

select tr_tp_cd, count(*) from BUSER.BCLT_CLS_SUB_DESC A
where a.acct_dt = '2011-12-20'
group by tr_tp_cd
;

select * from BUSER.BCLT_CLS_BASE B
where acct_dt = '2011-12-20'
;

-- 자동전표 계좌별 전표 확인
SELECT
   A.ACCT_DT
 , A.TR_DESC_NO
 , A.ACCT_DEPT_CD
 ,(SELECT Z.DEPT_NM
     FROM DUSER.DHRT_ORG Z
   WHERE Z.DEPT_CD = A.ACCT_DEPT_CD)  AS ACCT_DEPT_NM
 , A.TR_TP_CD
 ,(SELECT Z.CD_DESC_KOR_NM
      FROM GUSER.GBCT_COMM_CD_DESC Z
    WHERE Z.CD_KIND_NO = 'A00068'
     AND Z.CD_DESC_NO = A.TR_TP_CD)   AS TR_TP_NM    
 , CASE WHEN A.DC_DIV_CD = 'C' THEN '대변'
        ELSE '차변' END AS DC_DIV_CD
 , A.ACCT_CD
 , A.LOAN_NO
 , A.LOAN_SEQ
 , A.BANK_CD
 ,(SELECT Z.CD_DESC_KOR_NM
           FROM GUSER.GBCT_COMM_CD_DESC Z
          WHERE Z.CD_KIND_NO = 'A00003'
            AND Z.CD_DESC_NO = A.BANK_CD)        AS BANK_NM
 , A.ACNT_NO
 , A.VOCH_AMT
FROM
 BUSER.BCLT_CLS_SUB_DESC A
  INNER JOIN EUSER.EACT_ACCT B
   ON  A.ACCT_CD = B.ACCT_CD
   AND B.ACCT_YY = SUBSTR(A.ACCT_DT, 1, 4)
   AND B.MNG_NO_DIV_CD = '02'
where a.acct_dt = '2011-12-20'
--WHERE
-- ?condition
ORDER BY
 TR_DESC_NO, ACCT_DEPT_CD, TR_TP_CD
;

-- 자동전표 계좌 수정
select * from BUSER.BCLT_CLS_SUB_DESC
where acct_dt = '2011-12-19'
;

-- 자동전표 처리시 마감내역 조회
SELECT
 A.CMNG_NO
,A.CMNG_NO1
,A.CMNG_NO2
,A.ACCT_CD
,A.DC_DIV_CD
,A.MNG_NO_DIV_CD
,A.ACCT_DT
,A.ACCT_DEPT_CD
,A.TR_TP_CD
,A.TR_STAG_CD
,A.TRAN_TP_CD
,A.TRAN_NO
,A.MNG_DEPT_CD
,A.VOCH_AMT
,CASE WHEN A.ACCT_CD='23' THEN A.MNG_DEPT_CD WHEN A.ACCT_CD='14' THEN A.MNG_DEPT_CD ELSE A.MNG_NO END MNG_NO
,A.LOAN_NO
,A.LOAN_SEQ
,A.CNT-1 CNT
 FROM
(SELECT
 B.CMNG_NO
,B.CMNG_NO1
,B.CMNG_NO2
,A.ACCT_CD
,'D' DC_DIV_CD
,(SELECT C.MNG_NO_DIV_CD FROM EUSER.EACT_ACCT C WHERE A.ACCT_CD=C.ACCT_CD AND C.ACCT_YY=SUBSTR(?acctDt,1,4)) MNG_NO_DIV_CD
,MAX(A.ACCT_DT) ACCT_DT
,MAX(A.ACCT_DEPT_CD) ACCT_DEPT_CD
,MAX(A.TR_TP_CD) TR_TP_CD
,MAX(A.TR_STAG_CD) TR_STAG_CD
,MAX(A.TRAN_TP_CD) TRAN_TP_CD
,MAX(A.TRAN_NO) TRAN_NO
,MAX(A.MNG_DEPT_CD) MNG_DEPT_CD
,SUM(A.VOCH_AMT) VOCH_AMT
,CASE (SELECT C.MNG_NO_DIV_CD FROM EUSER.EACT_ACCT C WHERE A.ACCT_CD=C.ACCT_CD AND C.ACCT_YY=SUBSTR(?acctDt,1,4))
   WHEN '02' THEN (SELECT C.DEPO_NO FROM EUSER.EFDT_DEPO_BASE C WHERE REPLACE(C.ACNT_NO,'-','')=REPLACE(B.CMNG_NO2,'-',''))
   WHEN '06' THEN B.CMNG_NO1
   WHEN '08' THEN '20'
   ELSE ''
 END MNG_NO
,MAX(B.LOAN_NO) LOAN_NO
,MAX(B.LOAN_SEQ) LOAN_SEQ
,COUNT(B.LOAN_NO) CNT
 FROM BUSER.BCLT_CLS_SUB_DESC A
,(SELECT
 A.TR_DESC_NO
,MAX(CASE WHEN A.DC_DIV_CD='C' AND A.ACCT_CD='23' THEN A.MNG_DEPT_CD ELSE '' END) CMNG_NO
,MAX(CASE WHEN A.DC_DIV_CD='D' AND A.ACCT_CD='14' THEN A.MNG_DEPT_CD ELSE '' END) CMNG_NO1
,MAX(CASE WHEN A.DC_DIV_CD='D' AND A.ACCT_CD='11010101' THEN A.ACNT_NO ELSE '' END) CMNG_NO2
,MAX(A.LOAN_NO) LOAN_NO
,MAX(A.LOAN_SEQ) LOAN_SEQ
FROM BUSER.BCLT_CLS_BASE C,BUSER.BCLT_CLS_SUB_DESC A
WHERE C.ACCT_DT=?acctDt
AND C.ACCT_DEPT_CD=?acctDeptCd
AND C.TRAN_TP_CD=?tranTpCd
AND C.TRAN_NO=?tranNo
AND C.ACCT_UNIT_CD=?acctUnitCd
AND C.ACCT_DT=A.ACCT_DT
AND C.ACCT_DEPT_CD=A.ACCT_DEPT_CD
AND C.TRAN_TP_CD=A.TRAN_TP_CD
AND C.TRAN_NO=A.TRAN_NO
GROUP BY A.TR_DESC_NO) B
WHERE A.TR_DESC_NO=B.TR_DESC_NO
AND A.ACCT_DT=?acctDt
AND A.ACCT_DEPT_CD=?acctDeptCd
AND A.TRAN_TP_CD=?tranTpCd
AND A.TRAN_NO=?tranNo
AND A.ACCT_UNIT_CD=?acctUnitCd
AND A.DC_DIV_CD='D'
GROUP BY B.CMNG_NO,B.CMNG_NO1,B.CMNG_NO2,A.ACCT_CD
UNION 
SELECT B.CMNG_NO,B.CMNG_NO1,B.CMNG_NO2,A.ACCT_CD,'C' DC_DIV_CD
,(SELECT C.MNG_NO_DIV_CD FROM EUSER.EACT_ACCT C WHERE A.ACCT_CD=C.ACCT_CD AND C.ACCT_YY=SUBSTR(?acctDt,1,4)) MNG_NO_DIV_CD
,MAX(A.ACCT_DT) ACCT_DT,MAX(A.ACCT_DEPT_CD) ACCT_DEPT_CD,MAX(A.TR_TP_CD) TR_TP_CD,MAX(A.TR_STAG_CD) TR_STAG_CD
,MAX(A.TRAN_TP_CD) TRAN_TP_CD,MAX(A.TRAN_NO) TRAN_NO,MAX(A.MNG_DEPT_CD) MNG_DEPT_CD,SUM(A.VOCH_AMT) VOCH_AMT
,CASE (SELECT C.MNG_NO_DIV_CD FROM EUSER.EACT_ACCT C WHERE A.ACCT_CD=C.ACCT_CD AND C.ACCT_YY=SUBSTR(?acctDt,1,4))
  WHEN '02' THEN (SELECT C.DEPO_NO FROM EUSER.EFDT_DEPO_BASE C WHERE REPLACE(C.ACNT_NO,'-','')=REPLACE(B.CMNG_NO2,'-',''))
  WHEN '06' THEN B.CMNG_NO1
  WHEN '08' THEN '20'
  ELSE ''
 END MNG_NO
,MAX(B.LOAN_NO) LOAN_NO
,MAX(B.LOAN_SEQ) LOAN_SEQ
,COUNT(B.LOAN_NO) CNT
 FROM BUSER.BCLT_CLS_SUB_DESC A
,(SELECT A.TR_DESC_NO
,MAX(CASE WHEN A.DC_DIV_CD='C' AND A.ACCT_CD='23' THEN A.MNG_DEPT_CD ELSE '' END) CMNG_NO
,MAX(CASE WHEN A.DC_DIV_CD='D' AND A.ACCT_CD='14' THEN A.MNG_DEPT_CD ELSE '' END) CMNG_NO1
,MAX(CASE WHEN A.DC_DIV_CD='D' AND A.ACCT_CD='11010103' THEN A.ACNT_NO ELSE '' END) CMNG_NO2
,MAX(A.LOAN_NO) LOAN_NO
,MAX(A.LOAN_SEQ) LOAN_SEQ
 FROM
 BUSER.BCLT_CLS_BASE C
,BUSER.BCLT_CLS_SUB_DESC A
WHERE C.ACCT_DT=?acctDt
AND C.ACCT_DEPT_CD=?acctDeptCd
AND C.TRAN_TP_CD=?tranTpCd
AND C.TRAN_NO=?tranNo
AND C.ACCT_UNIT_CD=?acctUnitCd
AND C.ACCT_DT=A.ACCT_DT
AND C.ACCT_DEPT_CD=A.ACCT_DEPT_CD
AND C.TRAN_TP_CD=A.TRAN_TP_CD
AND C.TRAN_NO=A.TRAN_NO
GROUP BY A.TR_DESC_NO) B
WHERE A.TR_DESC_NO=B.TR_DESC_NO
AND A.ACCT_DT=?acctDt
AND A.ACCT_DEPT_CD=?acctDeptCd
AND A.TRAN_TP_CD=?tranTpCd
AND A.TRAN_NO=?tranNo
AND A.ACCT_UNIT_CD=?acctUnitCd
AND A.DC_DIV_CD='C'
GROUP BY B.CMNG_NO,B.CMNG_NO1,B.CMNG_NO2,A.ACCT_CD) A
WHERE A.VOCH_AMT!=0
;

