
select * from AUSER.ALOT_MO_ACNT_BASE
;

SELECT
	DATA_DIC_NO, TBL_NM, COND_STMT, SORT_STMT, DATA_DIC_TITL, INIT_READ_FG
 FROM
	 GUSER.GSCT_DATA_DIC
;

-- 은행 검색
select * from GUSER.GBCT_COMM_CD_DESC
WHERE CD_KIND_NO = 'A00003'
ORDER BY CD_DESC_NO ASC
;

--select * from 