/*
-----------------------------------------------------------------
	[마감 관리] - 자동전표이체처리 - 자동전표처리마감내역조회(자동이체)
		EACBS_CLSMNGBC	: 27
---------------------------------------------------------------*/	
SELECT
	A.MNG_DEPT_CD
	, A.ACCT_CD
	, A.ACNT_NO
	, A.ACCT_CD
	, A.DC_DIV_CD
	, C1.MNG_NO_DIV_CD
	, A.ACCT_DT
	, A.ACCT_DEPT_CD
	, A.TR_TP_CD
	, A.TR_STAG_CD
	, A.TRAN_TP_CD
	, A.TRAN_NO
	, A.OCCR_DEPT_CD
	, A.MNG_DEPT_CD
	, SUM(A.VOCH_AMT)	AS VOCH_AMT
	, DECODE(C1.MNG_NO_DIV_CD, '02', (SELECT C.DEPO_NO FROM EUSER.EFDT_DEPO_BASE C WHERE REPLACE(C.ACNT_NO, '-', '') = REPLACE(A.ACNT_NO , '-', ''))
							 , '06', (CASE  WHEN A.ACCT_DEPT_CD =  '100000' AND A.TRAN_TP_CD = 'B20' THEN A.MNG_DEPT_CD
							 				WHEN A.ACCT_DEPT_CD <> '100000' AND A.TRAN_TP_CD = 'B20' THEN A.OCCR_DEPT_CD
							 				ELSE A.MNG_DEPT_CD END)
							 , '08', '20'
							 , '')	AS MNG_NO
	, MAX(A.LOAN_NO)	AS LOAN_NO
	, MAX(A.LOAN_SEQ)	AS LOAN_SEQ
	, COUNT(A.LOAN_NO)	AS CNT
	, A.CPRT_COM_NO
	, A.ACCT_UNIT_CD
FROM
	BUSER.BCLT_CLS_SUB_DESC A
		LEFT OUTER JOIN EUSER.EACT_ACCT C1
			ON  A.ACCT_CD = C1.ACCT_CD
			AND C1.ACCT_YY = SUBSTR(?acctDt, 1, 4)
	, BUSER.BCLT_CLS_BASE B
WHERE
	B.ACCT_DT = ?acctDt
	AND B.ACCT_DEPT_CD = ?acctDeptCd
	AND B.TRAN_TP_CD = ?tranTpCd
	AND B.TRAN_NO = ?tranNo
	AND B.ACCT_UNIT_CD = ?acctUnitCd
	AND A.ACCT_DT = B.ACCT_DT
	AND A.ACCT_DEPT_CD = B.ACCT_DEPT_CD
	AND A.TRAN_TP_CD = B.TRAN_TP_CD
	AND A.TRAN_NO = B.TRAN_NO
	AND A.ACCT_UNIT_CD = B.ACCT_UNIT_CD
	AND A.VOCH_AMT > 0
GROUP BY
	A.ACCT_CD, A.ACCT_DT, A.ACNT_NO, A.DC_DIV_CD, C1.MNG_NO_DIV_CD, A.ACCT_DEPT_CD, A.TR_TP_CD, A.TR_STAG_CD
	, A.TRAN_TP_CD, A.TRAN_NO, A.MNG_DEPT_CD, A.CPRT_COM_NO, A.ACCT_UNIT_CD, A.OCCR_DEPT_CD

UNION ALL

SELECT
	A.MNG_DEPT_CD
	, A.ACCT_CD
	, A.ACNT_NO
	, A.ACCT_CD
	, A.DC_DIV_CD
	, C1.MNG_NO_DIV_CD
	, A.ACCT_DT
	, A.ACCT_DEPT_CD
	, A.TR_TP_CD
	, A.TR_STAG_CD
	, A.TRAN_TP_CD
	, A.TRAN_NO
	, A.OCCR_DEPT_CD
	, A.MNG_DEPT_CD
	, SUM(A.VOCH_AMT)	AS VOCH_AMT
	, DECODE(C1.MNG_NO_DIV_CD, '02', (SELECT C.DEPO_NO FROM EUSER.EFDT_DEPO_BASE C WHERE REPLACE(C.ACNT_NO, '-', '') = REPLACE(A.ACNT_NO, '-', ''))
							 , '06', (CASE  WHEN A.ACCT_DEPT_CD =  '100000' AND A.TRAN_TP_CD = 'B20' THEN A.MNG_DEPT_CD
							 				WHEN A.ACCT_DEPT_CD <> '100000' AND A.TRAN_TP_CD = 'B20' THEN A.OCCR_DEPT_CD
							 				ELSE A.MNG_DEPT_CD END)
							 , '08', '20'
							 , '')	AS MNG_NO
	, MAX(A.LOAN_NO)	AS LOAN_NO
	, MAX(A.LOAN_SEQ)	AS LOAN_SEQ
	, COUNT(A.LOAN_NO)	AS CNT
	, A.CPRT_COM_NO
	, A.ACCT_UNIT_CD
FROM
	BUSER.BCLT_CLS_SUB_DESC A
		LEFT OUTER JOIN EUSER.EACT_ACCT C1
			ON  A.ACCT_CD = C1.ACCT_CD
			AND C1.ACCT_YY = SUBSTR(?acctDt, 1, 4)
	, BUSER.BCLT_CLS_BASE B
WHERE
	B.ACCT_DT = ?acctDt
	AND B.ACCT_DEPT_CD = ?acctDeptCd
	AND B.TRAN_TP_CD = ?tranTpCd
	AND B.TRAN_NO = ?tranNo
	AND B.ACCT_UNIT_CD = ?acctUnitCd
	AND A.ACCT_DT = B.ACCT_DT
	AND A.ACCT_DEPT_CD = B.ACCT_DEPT_CD
	AND A.TRAN_TP_CD = B.TRAN_TP_CD
	AND A.TRAN_NO = B.TRAN_NO
	AND A.ACCT_UNIT_CD = B.ACCT_UNIT_CD
	AND A.VOCH_AMT < 0
GROUP BY
	A.ACCT_CD, A.ACCT_DT, A.ACNT_NO, A.DC_DIV_CD, C1.MNG_NO_DIV_CD, A.ACCT_DEPT_CD, A.TR_TP_CD, A.TR_STAG_CD
	, A.TRAN_TP_CD, A.TRAN_NO, A.MNG_DEPT_CD, A.CPRT_COM_NO, A.ACCT_UNIT_CD, A.OCCR_DEPT_CD
ORDER BY
	1, 2
;

-- 상단
SELECT
	A.MNG_DEPT_CD
	, A.ACCT_CD
	, A.ACNT_NO
	, A.ACCT_CD
	, A.DC_DIV_CD
	, C1.MNG_NO_DIV_CD
	, A.ACCT_DT
	, A.ACCT_DEPT_CD
	, A.TR_TP_CD
	, A.TR_STAG_CD
	, A.TRAN_TP_CD
	, A.TRAN_NO
	, A.OCCR_DEPT_CD
	, A.MNG_DEPT_CD
	, SUM(A.VOCH_AMT)	AS VOCH_AMT
	, DECODE(C1.MNG_NO_DIV_CD, '02', (SELECT C.DEPO_NO FROM EUSER.EFDT_DEPO_BASE C WHERE REPLACE(C.ACNT_NO, '-', '') = REPLACE(A.ACNT_NO , '-', ''))
							 , '06', (CASE  WHEN A.ACCT_DEPT_CD =  '100000' AND A.TRAN_TP_CD = 'B20' THEN A.MNG_DEPT_CD
							 				WHEN A.ACCT_DEPT_CD <> '100000' AND A.TRAN_TP_CD = 'B20' THEN A.OCCR_DEPT_CD
							 				ELSE A.MNG_DEPT_CD END)
							 , '08', '20'
							 , '')	AS MNG_NO
	, MAX(A.LOAN_NO)	AS LOAN_NO
	, MAX(A.LOAN_SEQ)	AS LOAN_SEQ
	, COUNT(A.LOAN_NO)	AS CNT
	, A.CPRT_COM_NO
	, A.ACCT_UNIT_CD
FROM
	BUSER.BCLT_CLS_SUB_DESC A
		LEFT OUTER JOIN EUSER.EACT_ACCT C1
			ON  A.ACCT_CD = C1.ACCT_CD
			AND C1.ACCT_YY = SUBSTR('2011', 1, 4)
	, BUSER.BCLT_CLS_BASE B
WHERE
	B.ACCT_DT = '2011-12-19' --?acctDt
--	AND B.ACCT_DEPT_CD = ?acctDeptCd
--	AND B.TRAN_TP_CD = ?tranTpCd
--	AND B.TRAN_NO = ?tranNo
--	AND B.ACCT_UNIT_CD = ?acctUnitCd
	AND A.ACCT_DT = B.ACCT_DT
	AND A.ACCT_DEPT_CD = B.ACCT_DEPT_CD
	AND A.TRAN_TP_CD = B.TRAN_TP_CD
	AND A.TRAN_NO = B.TRAN_NO
	AND A.ACCT_UNIT_CD = B.ACCT_UNIT_CD
	AND A.VOCH_AMT > 0
GROUP BY
	A.ACCT_CD, A.ACCT_DT, A.ACNT_NO, A.DC_DIV_CD, C1.MNG_NO_DIV_CD, A.ACCT_DEPT_CD, A.TR_TP_CD, A.TR_STAG_CD
	, A.TRAN_TP_CD, A.TRAN_NO, A.MNG_DEPT_CD, A.CPRT_COM_NO, A.ACCT_UNIT_CD, A.OCCR_DEPT_CD
ORDER BY
	1, 2
;

-- 하단
SELECT
	A.MNG_DEPT_CD
	, A.ACCT_CD
	, A.ACNT_NO
	, A.ACCT_CD
	, A.DC_DIV_CD
	, C1.MNG_NO_DIV_CD
	, A.ACCT_DT
	, A.ACCT_DEPT_CD
	, A.TR_TP_CD
	, A.TR_STAG_CD
	, A.TRAN_TP_CD
	, A.TRAN_NO
	, A.OCCR_DEPT_CD
	, A.MNG_DEPT_CD
	, SUM(A.VOCH_AMT)	AS VOCH_AMT
	, DECODE(C1.MNG_NO_DIV_CD, '02', (SELECT C.DEPO_NO FROM EUSER.EFDT_DEPO_BASE C WHERE REPLACE(C.ACNT_NO, '-', '') = REPLACE(A.ACNT_NO, '-', ''))
							 , '06', (CASE  WHEN A.ACCT_DEPT_CD =  '100000' AND A.TRAN_TP_CD = 'B20' THEN A.MNG_DEPT_CD
							 				WHEN A.ACCT_DEPT_CD <> '100000' AND A.TRAN_TP_CD = 'B20' THEN A.OCCR_DEPT_CD
							 				ELSE A.MNG_DEPT_CD END)
							 , '08', '20'
							 , '')	AS MNG_NO
	, MAX(A.LOAN_NO)	AS LOAN_NO
	, MAX(A.LOAN_SEQ)	AS LOAN_SEQ
	, COUNT(A.LOAN_NO)	AS CNT
	, A.CPRT_COM_NO
	, A.ACCT_UNIT_CD
FROM
	BUSER.BCLT_CLS_SUB_DESC A
		LEFT OUTER JOIN EUSER.EACT_ACCT C1
			ON  A.ACCT_CD = C1.ACCT_CD
			AND C1.ACCT_YY = SUBSTR('2011', 1, 4)
	, BUSER.BCLT_CLS_BASE B
WHERE
	B.ACCT_DT = '2011-12-19' --?acctDt
--	AND B.ACCT_DEPT_CD = ?acctDeptCd
--	AND B.TRAN_TP_CD = ?tranTpCd
--	AND B.TRAN_NO = ?tranNo
--	AND B.ACCT_UNIT_CD = ?acctUnitCd
	AND A.ACCT_DT = B.ACCT_DT
	AND A.ACCT_DEPT_CD = B.ACCT_DEPT_CD
	AND A.TRAN_TP_CD = B.TRAN_TP_CD
	AND A.TRAN_NO = B.TRAN_NO
	AND A.ACCT_UNIT_CD = B.ACCT_UNIT_CD
	AND A.VOCH_AMT < 0
GROUP BY
	A.ACCT_CD, A.ACCT_DT, A.ACNT_NO, A.DC_DIV_CD, C1.MNG_NO_DIV_CD, A.ACCT_DEPT_CD, A.TR_TP_CD, A.TR_STAG_CD
	, A.TRAN_TP_CD, A.TRAN_NO, A.MNG_DEPT_CD, A.CPRT_COM_NO, A.ACCT_UNIT_CD, A.OCCR_DEPT_CD
ORDER BY
	1, 2
;

-- 마감
SELECT COUNT(*) 
          FROM EUSER.EACT_FINC_CLS B 
         WHERE B.ACCT_DT <= '2011-12-19'
         ;
         
SELECT (SELECT COUNT(*) 
          FROM EUSER.EACT_FINC_CLS B 
         WHERE B.ACCT_DT <= '2011-12-19') --?clacYymm)
       -(SELECT COUNT(*) 
          FROM EUSER.EACT_FINC_CLS B 
        WHERE B.ACCT_DT <= '2011-12-19' --) --?clacYymm) - 
          AND B.ACCT_CLS_FG = '1')
   FROM  DUAL
;