
SELECT
   A.ACCT_DT
 , A.TR_DESC_NO
 , A.ACCT_DEPT_CD
 ,(SELECT Z.DEPT_NM
     FROM DUSER.DHRT_ORG Z
   WHERE Z.DEPT_CD = A.ACCT_DEPT_CD)  AS ACCT_DEPT_NM
 , A.TR_TP_CD
 ,(SELECT Z.CD_DESC_KOR_NM
      FROM GUSER.GBCT_COMM_CD_DESC Z
    WHERE Z.CD_KIND_NO = 'A00068'
     AND Z.CD_DESC_NO = A.TR_TP_CD)   AS TR_TP_NM    
       
 , CASE WHEN A.DC_DIV_CD = 'C' THEN '대변'
        ELSE '차변' END AS DC_DIV_CD
 , A.ACCT_CD
 , A.LOAN_NO
 , A.LOAN_SEQ
 , A.BANK_CD
 ,(SELECT Z.CD_DESC_KOR_NM
           FROM GUSER.GBCT_COMM_CD_DESC Z
          WHERE Z.CD_KIND_NO = 'A00003'
            AND Z.CD_DESC_NO = A.BANK_CD)        AS BANK_NM
 , A.ACNT_NO
 , A.VOCH_AMT
FROM
 BUSER.BCLT_CLS_SUB_DESC A
  INNER JOIN EUSER.EACT_ACCT B
   ON  A.ACCT_CD = B.ACCT_CD
   AND B.ACCT_YY = SUBSTR(A.ACCT_DT, 1, 4)
   AND B.MNG_NO_DIV_CD = '02'
WHERE
    a.acct_dt = '2011-12-16'
--  A.ACCT_CD = B.ACCT_CD
--  and 
-- ?condition
ORDER BY
 TR_DESC_NO, ACCT_DEPT_CD, TR_TP_CD
;



select * from BUSER.BCLT_CLS_SUB_DESC
where acct_dt = '2011-12-15'
;


