-- CHK_SUB_DESC_AMT
SELECT
    CASE WHEN A.NO = 1 THEN B.SETL_AMT
          WHEN A.NO = 2 THEN B.DEPO
          WHEN A.NO = 3 THEN B.CASH
          WHEN A.NO = 4 THEN B.DSRC_ADJ_AMT
          WHEN A.NO = 5 THEN B.DSRC_OCCR_AMT
          WHEN A.NO = 6 THEN B.PAMT
          WHEN A.NO = 7 THEN B.INT
          WHEN A.NO = 8 THEN B.DFEE
          WHEN A.NO = 9 THEN B.ADJ_DFEE
          WHEN A.NO = 10 THEN B.PDUE_DISC_DFEE
          WHEN A.NO = 11 THEN B.LEGL_ACTN_COST
          WHEN A.NO = 12 THEN B.MID_RMBR_FEE
          WHEN A.NO = 13 THEN B.TRT_FEE_DISC
          WHEN A.NO = 14 THEN B.ETC_PRFT
          WHEN A.NO = 15 THEN B.EXMP_PAMT
          WHEN A.NO = 16 THEN B.EXMP_INT
          WHEN A.NO = 17 THEN B.EXMP_DFEE
          WHEN A.NO = 18 THEN B.EXMP_LEGL_ACTN_COST
          WHEN A.NO = 19 THEN B.EXMP_MID_RMBR_FEE
          WHEN A.NO = 20 THEN B.CRDT_RCVR_UNRCV_AMT
          WHEN A.NO = 21 THEN B.PSG_INT
          WHEN A.NO = 22 THEN B.PRE_RCPT_PAMT
          WHEN A.NO = 23 THEN B.PRE_RCPT_INT
          WHEN A.NO = 24 THEN B.PAY_AMT
          WHEN A.NO = 25 THEN B.RETN_AMT
          WHEN A.NO = 26 THEN B.CHNG_BF_FEE_COST_TRT_FEE
          WHEN A.NO = 27 THEN B.CHNG_BF_FEE_PRFT_TRT_FEE
          WHEN A.NO = 28 THEN B.CHNG_BF_PAMT
          WHEN A.NO = 29 THEN B.CHNG_BF_DFER_COST_CPRT_FEE
          WHEN A.NO = 30 THEN B.CHNG_BF_DFER_COST_TRT_FEE
          WHEN A.NO = 31 THEN B.CHNG_BF_DFER_PRFT_CPRT_FEE
          WHEN A.NO = 32 THEN B.CHNG_BF_DFER_PRFT_TRT_FEE
          WHEN A.NO = 33 THEN B.CHNG_BF_INT_COST_CPRT_FEE
          WHEN A.NO = 34 THEN B.CHNG_BF_INT_PRFT_CPRT_FEE
          WHEN A.NO = 35 THEN B.CHNG_AF_FEE_COST_TRT_FEE
          WHEN A.NO = 36 THEN B.CHNG_AF_FEE_PRFT_TRT_FEE
          WHEN A.NO = 37 THEN B.CHNG_AF_PAMT
          WHEN A.NO = 38 THEN B.CHNG_AF_DFER_COST_CPRT_FEE
          WHEN A.NO = 39 THEN B.CHNG_AF_DFER_COST_TRT_FEE
          WHEN A.NO = 40 THEN B.CHNG_AF_DFER_PRFT_CPRT_FEE
          WHEN A.NO = 41 THEN B.CHNG_AF_DFER_PRFT_TRT_FEE
          WHEN A.NO = 42 THEN B.CHNG_AF_INT_COST_CPRT_FEE
          WHEN A.NO = 43 THEN B.CHNG_AF_INT_PRFT_CPRT_FEE
          WHEN A.NO = 44 THEN B.FEE_COST_TRT_FEE
          WHEN A.NO = 45 THEN B.FEE_PRFT_TRT_FEE
          WHEN A.NO = 46 THEN B.DFER_COST_CPRT_FEE
          WHEN A.NO = 47 THEN B.DFER_COST_TRT_FEE
          WHEN A.NO = 48 THEN B.DFER_PRFT_CPRT_FEE
          WHEN A.NO = 49 THEN B.DFER_PRFT_TRT_FEE
          WHEN A.NO = 50 THEN B.INT_COST_CPRT_FEE
          WHEN A.NO = 51 THEN B.INT_PRFT_CPRT_FEE
          WHEN A.NO = 52 THEN B.NOTA_FEE
          WHEN A.NO = 53 THEN B.STMP_FEE
          WHEN A.NO = 54 THEN B.HTAX
          WHEN A.NO = 55 THEN B.SET_FEE
          WHEN A.NO = 56 THEN B.ITAX
          WHEN A.NO = 57 THEN B.ETC_FEE
          WHEN A.NO = 58 THEN B.DEBTMAN_FEE
          WHEN A.NO = 59 THEN B.PR_FEE
          WHEN A.NO = 60 THEN B.TRT_FEE
          WHEN A.NO = 61 THEN B.BAD_DEBT_APPR_AMT
          WHEN A.NO = 62 THEN B.BAD_DEBT_DEPR_COST
          WHEN A.NO = 63 THEN B.DEPS_AMT
          WHEN A.NO = 64 THEN B.ETC_LOSS
          ELSE 0
    END                                                       AMT
FROM BUSER.BGMT_COMM_DUMMY A
    ,BUSER.BCLT_CLS_TR_DESC B
WHERE A.NO <= (SELECT TO_NUMBER(MAX(CD_DESC_NO))
               FROM GUSER.GBCT_COMM_CD_DESC Z
              WHERE Z.CD_KIND_NO = 'R00044')
AND B.ACCT_DT    = '2011-12-19'
AND B.TR_DESC_NO = '26994' --'27006'
;

SELECT TO_NUMBER(MAX(CD_DESC_NO))
FROM GUSER.GBCT_COMM_CD_DESC Z
WHERE Z.CD_KIND_NO = 'R00044'
;

SELECT *
FROM GUSER.GBCT_COMM_CD_DESC Z
WHERE Z.CD_KIND_NO = 'R00044'
;

select * 
from BUSER.BCLT_CLS_TR_DESC B
WHERE
--    A.NO <= (SELECT TO_NUMBER(MAX(CD_DESC_NO))
--               FROM GUSER.GBCT_COMM_CD_DESC Z
--              WHERE Z.CD_KIND_NO = 'R00044')
 B.ACCT_DT    = '2011-12-19'
AND B.TR_DESC_NO = '26994' --'27006'
;
