#!/bin/sh

prefix=`date '+%Y%m%d_%H%M'`

send_id="$(ps -ef | grep 'SendDaemon 9530' |grep -v grep | grep -v tail)"

if [ ! "${send_id}" = "" ]; then
    echo "Kib Daemon Already Start!!!!!";
#    exit;
fi;

mv /HIC_APP/daemon/log_opr/kib_9530.log /HIC_APP/daemon/log_opr/kib_9530_${prefix}.log
nohup java -Xmx256m -classpath /HIC_APP/daemon/lib/xutil.jar:/HIC_APP/daemon/class ssvr.SendDaemon 9530 192.168.4.100 50811 >> /HIC_APP/daemon/log_opr/kib_9530.log &
