#!/bin/sh

prefix=`date '+%Y%m%d_%H%M'`

send_id="$(ps -ef | grep 9530)"

if [ ! "${send_id}" = "" ]; then
    echo "Kib Daemon Already Start!!!!!";
#    exit;
fi;

mv /HIC_APP/daemon/log_opr/kib.log /HIC_APP/daemon/log_opr/kib${prefix}.log
nohup java -Xmx256m -classpath /HIC_APP/daemon/lib/xutil.jar:/HIC_APP/daemon/class ssvr.SendDaemon 9530 192.168.4.100 50811 >> /HIC_APP/daemon/log_opr/kib.log &
