#!/bin/sh

prefix=`date '+%Y%m%d_%H%M'`

send_id="$(ps -ef | grep 'ReceiveDaemon 9810' | grep -v grep | grep -v tail)"

if [ ! "${send_id}" = "" ]; then
    echo "Kibrsvr9810 Daemon Already Start!!!!!";
#    exit;
fi;

mv /HIC_APP/daemon/log_opr/kibrsvr_9810.log /HIC_APP/daemon/log_opr/kibrsvr_9810_${prefix}.log
nohup java -Xmx256m -classpath /HIC_APP/daemon/lib/xutil.jar:/HIC_APP/daemon/class rsvr.ReceiveDaemon 9810 172.20.101.41 9800 >> /HIC_APP/daemon/log_opr/kibrsvr_9810.log &
