#!/bin/sh

send_id="$(ps -ef | grep 'ReceiveDaemon 9810' | grep -v grep | grep -v tail | cut -c10-16)";

if [ ! "${send_id}" = "" ]; then
	kill -9 ${send_id};
	echo "Kibrsvr9810 Daemon Down !!";
else 
	echo "Already Kibrsvr9810 Daemon Down!!"
fi;
