#!/bin/sh

send_id="$(ps -ef | grep 'ReceiveDaemon 10800' | grep -v grep | grep -v tail | cut -c10-16)";

if [ ! "${send_id}" = "" ]; then
	kill -9 ${send_id};
	echo "Kibrsvr10800 Daemon Down !!";
else 
	echo "Already Kibrsvr10800 Daemon Down!!"
fi;
